/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prototype.Courses;

/**
 *
 * @author ahooper
 */
public class Courses_AddOrEditPanel extends javax.swing.JPanel {

    /**
     * Creates new form Courses_AddOrEdit
     */
    public Courses_AddOrEditPanel() {
        initComponents();
    }
    
//    public Courses_AddOrEditPanel(Object[] params) {
//        initComponents();
//        
//        courseNumTextbox.setText(params[0].toString());
//        sectionTextbox.setText(params[1].toString());
//        
//        String[] timeDay = params[2].toString().split(" ");
//        
//        
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        courseNumTextbox = new javax.swing.JTextField();
        instructorTextbox = new javax.swing.JTextField();
        sectionTextbox = new javax.swing.JTextField();
        courseNumLabel = new javax.swing.JLabel();
        instructorLabel = new javax.swing.JLabel();
        sectionLabel = new javax.swing.JLabel();
        lookupInstructorButton = new javax.swing.JButton();
        daysPanel = new javax.swing.JPanel();
        mondayCheckbox = new javax.swing.JCheckBox();
        tuesdayCheckbox = new javax.swing.JCheckBox();
        wednesdayCheckbox = new javax.swing.JCheckBox();
        thursdayCheckbox = new javax.swing.JCheckBox();
        fridayCheckbox = new javax.swing.JCheckBox();
        saturdayCheckbox = new javax.swing.JCheckBox();
        sundayCheckbox = new javax.swing.JCheckBox();
        daysLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        timeTextbox = new javax.swing.JTextField();
        timeLabel = new javax.swing.JLabel();

        courseNumLabel.setText("Course Number:");

        instructorLabel.setText("Instructor:");

        sectionLabel.setText("Section:");

        lookupInstructorButton.setText("Lookup..");

        daysPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        mondayCheckbox.setText("Monday");

        tuesdayCheckbox.setText("Tuesday");

        wednesdayCheckbox.setText("Wednesday");

        thursdayCheckbox.setText("Thursday");

        fridayCheckbox.setText("Friday");

        saturdayCheckbox.setText("Saturday");

        sundayCheckbox.setText("Sunday");

        javax.swing.GroupLayout daysPanelLayout = new javax.swing.GroupLayout(daysPanel);
        daysPanel.setLayout(daysPanelLayout);
        daysPanelLayout.setHorizontalGroup(
            daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daysPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(daysPanelLayout.createSequentialGroup()
                        .addComponent(wednesdayCheckbox)
                        .addGap(18, 18, 18)
                        .addComponent(sundayCheckbox))
                    .addComponent(thursdayCheckbox)
                    .addGroup(daysPanelLayout.createSequentialGroup()
                        .addGroup(daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mondayCheckbox)
                            .addComponent(tuesdayCheckbox))
                        .addGap(34, 34, 34)
                        .addGroup(daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fridayCheckbox)
                            .addComponent(saturdayCheckbox))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        daysPanelLayout.setVerticalGroup(
            daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daysPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mondayCheckbox)
                    .addComponent(fridayCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tuesdayCheckbox)
                    .addComponent(saturdayCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(daysPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wednesdayCheckbox)
                    .addComponent(sundayCheckbox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thursdayCheckbox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        daysLabel.setText("Days:");

        submitButton.setText("Submit");

        timeLabel.setText("Time:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(daysLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(daysPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sectionLabel)
                                .addGap(8, 8, 8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(instructorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(courseNumLabel)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(timeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeTextbox)
                            .addComponent(sectionTextbox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(instructorTextbox)
                            .addComponent(courseNumTextbox))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lookupInstructorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseNumTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(courseNumLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(instructorTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(instructorLabel)
                    .addComponent(lookupInstructorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sectionTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sectionLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeTextbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(daysPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(daysLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel courseNumLabel;
    private javax.swing.JTextField courseNumTextbox;
    private javax.swing.JLabel daysLabel;
    private javax.swing.JPanel daysPanel;
    private javax.swing.JCheckBox fridayCheckbox;
    private javax.swing.JLabel instructorLabel;
    private javax.swing.JTextField instructorTextbox;
    private javax.swing.JButton lookupInstructorButton;
    private javax.swing.JCheckBox mondayCheckbox;
    private javax.swing.JCheckBox saturdayCheckbox;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JTextField sectionTextbox;
    private javax.swing.JButton submitButton;
    private javax.swing.JCheckBox sundayCheckbox;
    private javax.swing.JCheckBox thursdayCheckbox;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField timeTextbox;
    private javax.swing.JCheckBox tuesdayCheckbox;
    private javax.swing.JCheckBox wednesdayCheckbox;
    // End of variables declaration//GEN-END:variables
}
